version: '3'

services:
  node:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./server:/usr/src/app/server
      - ./build/:/usr/src/app/build
      - ./.yarn_cache:/usr/src/app/.yarn_cache
      - ./package.json:/usr/src/app/package.json
      - ./integrations-demo/:/usr/src/app/integrations-demo
      - ./docker-cmd.sh:/usr/src/app/docker-cmd.sh
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: ${NETWORK}
