import React from 'react';
import {Box, Divider, Drawer, List, Typography, useTheme} from '@mui/material';
import {
  OndemandVideoRounded as VideoIcon,
  DirectionsRunRounded as AnimationIcon
} from '@mui/icons-material';
import {useDispatch, useSelector} from 'react-redux';
import {NavLink} from 'react-router-dom';
import {selectIsDrawerOpen} from '../../reducers';
import {setDrawerState} from '../../actions';
import DrawerItem from '../DrawerItem';
import routes from '../../../../routes';
import {APP_BAR_HEIGHT} from '../../../../../config/constants';

export const AppDrawer = () => {
  const dispatch = useDispatch();
  const theme = useTheme();
  // const isInitialized = useSelector(selectIsAnimationInitialized);
  const isDrawerOpen = useSelector(selectIsDrawerOpen);
  return (
    <Drawer
      anchor={'left'}
      open={isDrawerOpen}
      onClose={() => dispatch(setDrawerState(false))}>
      <Box paddingX={2}>
        <Typography
          variant={'h4'}
          height={APP_BAR_HEIGHT}
          alignItems={'center'}
          justifyContent={'center'}
          display={'flex'}
          color={theme.palette.text.secondary}>
          Discover&nbsp;<b>Animation Tool</b>
        </Typography>
        <Divider sx={{marginBottom: 2}} />
        <nav aria-label='Animation tool menu'>
          <List>
            <DrawerItem
              primary={'Animate dataset'}
              secondary={
                <>
                  generated by <b>LearningHub</b> or <b>Tensor flow</b>
                </>
              }
              icon={<AnimationIcon />}
              component={NavLink}
              componentProps={{
                to: routes.root
              }}
            />
            <DrawerItem
              primary={'Generate dataset'}
              secondary={
                <>
                  from an <b>mp4</b> video file
                </>
              }
              icon={<VideoIcon />}
              component={NavLink}
              componentProps={{
                to: routes.estimate
              }}
            />
          </List>
        </nav>
      </Box>
    </Drawer>
  );
};

export default AppDrawer;
